### ISSUE TITLE
EnvProviderManagerTest fails with latest version of JUnit on TravisCI w/ multiple JDKs

### ISSUE THREAD

**Issue by silkentrance** [coldrye-java/junit-testing#28]
EnvProviderManager#prepareEnviromentProviders() will be called 5 times instead of just 1.
This has not been the case before and it might be related to upgrading JUnit/Mockito dependencies to their latest versions.

Running the test locally does not show that behaviour.

On TravisCI, however, the test will fail on all of the targeted JDKs:

```
[ERROR] Failures: 
[ERROR]   EnvProviderManagerTest.prepareEnvironmentsMustCallUponCollector:80 
No interactions wanted here:
-> at eu.coldrye.junit.env.EnvProviderManagerTest.prepareEnvironmentsMustCallUponCollector(EnvProviderManagerTest.java:80)
But found this interaction on mock 'Mock for ExtensionContext, hashCode: 804104750':
-> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:133)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at eu.coldrye.junit.env.EnvProviderManager.isPrepared(EnvProviderManager.java:192)
2. -> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:128)
3. [?]-> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:133)
4. [?]-> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:133)
5. [?]-> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:133)
6. [?]-> at eu.coldrye.junit.env.EnvProviderManager.prepareEnvironmentProviders(EnvProviderManager.java:133)
```

**Comment by silkentrance** [comment]
Turns out that the prepared instance of the env provider was added multiple times, now it will be added once for each test class and thread.

**Comment by silkentrance** [comment]
Done in #27

**Comment by silkentrance** [comment]
jacoco fails on openjdk11, disabling openjdk11 for now

**Comment by silkentrance** [comment]
problem still prevails, local builds agains current 1.8 jdk will work while builds on travis still fail

**Comment by silkentrance** [comment]
heck, now it is working again. it seems since introduction of the github market place, the free version of travis is becoming more and more unreliable.

**Comment by silkentrance** [comment]
Builds are failing again. Somehow this fix did not work out. Have to investigate further. During the tests, the mock should no longer be called multiple times.

**Comment by silkentrance** [comment]
The existing tests were just off. The Mockito assertions would have never worked.

**Comment by silkentrance** [comment]
Setting the collector directly instead of setting it via EnvProviderManager.getInstance(collector) did the trick. Seems as if latest JUnit calls the BeforeEach/AfterEach from a different thread... However, applying the latest fix did the trick and the tests work as expected.
